import type {
  ActivityLog,
  Announcement,
  Complaint,
  DashboardStats,
  Incident,
  Notification,
} from "@/types";

export const MOCK_STATS: DashboardStats = {
  totalComplaints: 1247,
  pendingComplaints: 89,
  activeIncidents: 12,
  criticalIncidents: 3,
  totalUsers: 3456,
  departmentCount: 5,
  resolvedToday: 24,
  notificationsUnread: 7,
};

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: "1",
    reference_number: "CMP-20260515-A1B2C3",
    user_id: "u1",
    title: "Potholes on National Highway",
    description: "Large potholes causing traffic hazards near Ipil town center.",
    category: "roads",
    status: "pending",
    municipality: "Ipil",
    barangay: "Poblacion",
    image_url: null,
    assigned_department_id: null,
    admin_response: null,
    resolved_at: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    reference_number: "CMP-20260514-D4E5F6",
    user_id: "u2",
    title: "Flooding in Barangay Lower Taway",
    description: "Heavy rain caused flooding affecting 15 households.",
    category: "flooding",
    status: "under_review",
    municipality: "Ipil",
    barangay: "Lower Taway",
    image_url: null,
    assigned_department_id: null,
    admin_response: "DRRM team dispatched for assessment.",
    resolved_at: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    reference_number: "CMP-20260513-G7H8I9",
    user_id: "u3",
    title: "Garbage collection missed",
    description: "No garbage collection for 2 weeks in our area.",
    category: "garbage",
    status: "resolved",
    municipality: "Kabasalan",
    barangay: "Poblacion",
    image_url: null,
    assigned_department_id: null,
    admin_response: "Collection schedule restored.",
    resolved_at: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "1",
    reference_number: "INC-20260515-X1Y2Z3",
    reported_by: "u1",
    title: "Flash Flood Alert - Siay",
    description: "Rising water levels in low-lying areas. Evacuation recommended.",
    category: "flood",
    severity: "critical",
    status: "active",
    municipality: "Siay",
    barangay: "Balucanan",
    latitude: null,
    longitude: null,
    image_url: null,
    is_emergency: true,
    resolved_at: null,
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    reference_number: "INC-20260514-A2B3C4",
    reported_by: "u2",
    title: "Grass Fire - Diplahan",
    description: "Brush fire near agricultural area, contained.",
    category: "fire",
    severity: "medium",
    status: "responding",
    municipality: "Diplahan",
    barangay: "Poblacion",
    latitude: null,
    longitude: null,
    image_url: null,
    is_emergency: false,
    resolved_at: null,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    reference_number: "INC-20260513-D5E6F7",
    reported_by: "u3",
    title: "Vehicle Accident - Highway",
    description: "Two-vehicle collision, injuries reported.",
    category: "accident",
    severity: "high",
    status: "reported",
    municipality: "Ipil",
    barangay: null,
    latitude: null,
    longitude: null,
    image_url: null,
    is_emergency: true,
    resolved_at: null,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    user_id: null,
    title: "Critical Flood Alert",
    message: "DRRM has issued a critical alert for Siay municipality.",
    type: "alert",
    is_read: false,
    is_broadcast: true,
    link_url: "/admin/incidents",
    created_at: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "2",
    user_id: null,
    title: "New Complaint Assigned",
    message: "Complaint CMP-20260515-A1B2C3 requires department review.",
    type: "complaint_update",
    is_read: false,
    is_broadcast: false,
    link_url: "/admin/complaints",
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "3",
    user_id: null,
    title: "Provincial Assembly Announcement",
    message: "State of the Province Address scheduled for May 20, 2026.",
    type: "announcement",
    is_read: true,
    is_broadcast: true,
    link_url: "/announcements",
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "1",
    title: "Disaster Preparedness Week 2026",
    content:
      "The Provincial Government of Zamboanga Sibugay announces Disaster Preparedness Week from May 20-27, 2026. All municipalities are encouraged to conduct drills and review emergency protocols.",
    is_published: true,
    published_at: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "2",
    title: "ZSSPGP Citizen Portal Now Live",
    content:
      "Citizens can now submit complaints, track status, and receive alerts through the Smart Provincial Governance Platform. Register today for full access.",
    is_published: true,
    published_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "3",
    title: "Agricultural Support Program Applications Open",
    content:
      "The Provincial Agriculture Office is accepting applications for the 2026 crop support program. Visit your municipal agriculture office for details.",
    is_published: true,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: "1",
    user_id: "u1",
    action: "Submitted complaint",
    entity_type: "complaint",
    entity_id: "1",
    details: { reference: "CMP-20260515-A1B2C3" },
    created_at: new Date(Date.now() - 3600000).toISOString(),
    user: { id: "u1", email: "citizen@email.com", full_name: "Juan Dela Cruz", role: "citizen", department_id: null, phone: null, municipality: "Ipil", barangay: null, avatar_url: null, is_active: true, created_at: "" },
  },
  {
    id: "2",
    user_id: "u2",
    action: "Reported critical incident",
    entity_type: "incident",
    entity_id: "1",
    details: { severity: "critical" },
    created_at: new Date(Date.now() - 1800000).toISOString(),
    user: { id: "u2", email: "drrm@zsspgp.gov.ph", full_name: "Maria Santos", role: "department_admin", department_id: null, phone: null, municipality: null, barangay: null, avatar_url: null, is_active: true, created_at: "" },
  },
  {
    id: "3",
    user_id: "u3",
    action: "Resolved complaint",
    entity_type: "complaint",
    entity_id: "3",
    details: { status: "resolved" },
    created_at: new Date(Date.now() - 7200000).toISOString(),
    user: { id: "u3", email: "admin@zsspgp.gov.ph", full_name: "Gov. Admin", role: "governor_super_admin", department_id: null, phone: null, municipality: null, barangay: null, avatar_url: null, is_active: true, created_at: "" },
  },
];

export const CHART_COMPLAINTS_BY_CATEGORY = [
  { name: "Roads", value: 320 },
  { name: "Flooding", value: 245 },
  { name: "Health", value: 180 },
  { name: "Garbage", value: 156 },
  { name: "Water", value: 142 },
  { name: "Electricity", value: 98 },
  { name: "Others", value: 106 },
];

export const CHART_INCIDENTS_TREND = [
  { month: "Jan", incidents: 8 },
  { month: "Feb", incidents: 12 },
  { month: "Mar", incidents: 15 },
  { month: "Apr", incidents: 10 },
  { month: "May", incidents: 18 },
];

export const CHART_MUNICIPALITY_ACTIVITY = [
  { municipality: "Ipil", complaints: 245, incidents: 18 },
  { municipality: "Kabasalan", complaints: 156, incidents: 8 },
  { municipality: "Siay", complaints: 134, incidents: 12 },
  { municipality: "Diplahan", complaints: 98, incidents: 6 },
  { municipality: "Buug", complaints: 87, incidents: 5 },
];
